[project]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
name = "pygfx_sandbox"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
cube = "python flying_cube.py"
teapot = "python flying_teapot.py"
demo = [{ task = "cube" }]
robot-arm = "python robot_arm.py"
generate-meshes = "python generate-meshes.py"
pendulum = "python pendulum.py"
chariot = "python chariot.py"
ball = "python ball.py"
bicycle = "python bicycle.py"

[dependencies]
python = ">=3.13.2,<3.14"
pyglfw = ">=2.8.0,<3"
glfw = ">=3.4,<4"
scipy = ">=1.15.2,<2"
numpy = ">=2.2.6,<3"
rendercanvas = ">=2.1.2,<3"
trimesh = ">=4.6.10,<5"
libgfortran = ">=14.2.0,<16"
pytorch = ">=2.7.1,<3"

[pypi-dependencies]
sdf = { git = "https://github.com/fogleman/sdf.git" }
pyside6 = ">=6.9.0, <7"
pygfx = ">=0.10.0, <0.11"

